# roles/zsh/tasks/main.yml
- name: Install zsh
  apt:
    name: zsh
    state: present

- name: Find zsh path
  ansible.builtin.command: which zsh
  register: zsh_path
  changed_when: false

- name: Install oh-my-zsh
  become: true
  become_user: "{{ current_user.stdout }}"
  ansible.builtin.shell: |
    RUNZSH=no CHSH=no \
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  args:
    creates: "{{ ansible_env.HOME }}/.oh-my-zsh"

- name: Install zsh plugins
  become_user: "{{ current_user.stdout }}"
  git:
    repo: "{{ item.repo }}"
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/{{ item.path }}"
  loop:
    - { repo: "https://github.com/romkatv/powerlevel10k.git", path: "themes/powerlevel10k" }
    - { repo: "https://github.com/zsh-users/zsh-autosuggestions.git", path: "plugins/zsh-autosuggestions" }
    - { repo: "https://github.com/zsh-users/zsh-syntax-highlighting.git", path: "plugins/zsh-syntax-highlighting" }

- name: Change default shell to zsh
  become: true
  shell: "chsh -s $(which zsh) {{ current_user.stdout }}"
