# roles/zsh/tasks/main.yml
- name: Install zsh
  apt:
    name: zsh
    state: present

- name: Find zsh path
  ansible.builtin.command: which zsh
  register: zsh_path
  changed_when: false

- name: Change default shell to zsh
  become: true
  shell: "chsh -s $(which zsh) {{ current_user.stdout }}"

- name: Install oh-my-zsh
  become: true
  ansible.builtin.command: echo 'y' | su - {{ current_user.stdout }} -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

- name: Install zsh plugins
  git:
    repo: "{{ item.repo }}"
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/{{ item.path }}"
  loop:
    - { repo: "https://github.com/romkatv/powerlevel10k.git", path: "themes/powerlevel10k" }
    - { repo: "https://github.com/zsh-users/zsh-autosuggestions.git", path: "plugins/zsh-autosuggestions" }
    - { repo: "https://github.com/zsh-users/zsh-syntax-highlighting.git", path: "plugins/zsh-syntax-highlighting" }


