# roles/nnn/tasks/main.yml
- name: Clone nnn
  git:
    repo: https://github.com/jarun/nnn.git
    dest: /opt/nnn
    depth: 1

- name: Build nnn
  command: make O_NERD=1
  args:
    chdir: /opt/nnn
    creates: /opt/nnn/nnn

- name: Install nnn
  copy:
    src: /opt/nnn/nnn
    dest: /usr/local/bin/nnn
    mode: "0755"
    remote_src: yes

- name: Cleanup
  file:
    path: /opt/nnn
    state: absent
