# roles/dotfiles/tasks/main.yml
- name: Ensure config dir
  file:
    path: "{{ ansible_env.HOME }}/.config"
    state: directory

- name: Ensure config dir
  file:
    path: "{{ ansible_env.HOME }}/.config/kitty"
    state: directory

- name: Install zshrc
  copy:
    src: zshrc
    dest: "{{ ansible_env.HOME }}/.zshrc"

- name: Install aliases
  copy:
    src: aliases.zsh
    dest: "{{ ansible_env.HOME }}/.aliases.zsh"

- name: Install env
  copy:
    src: env.zsh
    dest: "{{ ansible_env.HOME }}/.env.zsh"

- name: Install p10k
  copy:
    src: p10k.zsh
    dest: "{{ ansible_env.HOME }}/.p10k.zsh"

- name: Install tmux
  copy:
    src: tmux.conf
    dest: "{{ ansible_env.HOME }}/.tmux.conf"

- name: Install vim config
  copy:
    src: vimrc
    dest: "{{ ansible_env.HOME }}/.vimrc"

- name: Install kitty config
  copy:
    src: kitty.conf
    dest: "{{ ansible_env.HOME }}/.config/kitty/kitty.conf"
