- hosts: localhost
  pre_tasks:
    - name: Register current user
      shell: whoami
      register: current_user

- hosts: localhost
  vars_prompt:
    - name: choice_upgrade_distro
      prompt: "Do you want to upgrade your distro? [y/N]"
      private: false

- hosts: all
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/local/go/bin"
  
  become: true
  roles:
    - base
    - fonts
    - golang
    - network-doctor
    - nnn
    - zsh
    - mint_themes
    - kitty
    - htop
    - lsd
    - fastfetch

- hosts: localhost
  tags: dotfiles
  become: false
  roles:
    - dotfiles
