# Prefix
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Mouse support
set -g mouse on

# Refresh every second
set -g status-interval 1

# Colors
set -g status-style fg=#C792EA,bg=default

# Right (also contains centered user@host)
set -g status-right "#[align=absolute-centre] #{client_user}@#H #[align=right] "
set -ga status-right "#(for b in /sys/class/power_supply/BAT*/capacity; do [ -f \"$b\" ] && printf '%s%% | ' \"$(cat \"$b\")\" && break; done)%d/%m/%Y %H:%M:%S"

set -g status-right-length 65
